version: '3'
services:
  database:
    image: mysql/mysql-server:8.0.31
    ports:
      - "3999:3306"
    environment:
      MYSQL_DATABASE: matchmaker
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
